### ISSUE TITLE
move docker-selinux to @projectatomic ?

### ISSUE THREAD

**Issue by lsm5** [fedora-cloud/docker-selinux#13]
just wondering if this one's best moved to @projectatomic since that's where our docker branches live. No big deal, but it'll help make some minor simplifactions to our rpm spec.

**Comment by lsm5** [comment]
@rhatdan @wrabcak

**Comment by rhatdan** [comment]
It would be fine with me. But @wrabcak owns it.

**Comment by wrabcak** [comment]
Yes, we can move it. @lsm5 do you have proper rights for that?

**Comment by lsm5** [comment]
Not me, i think @rhatdan can do it. He's admin on both orgs.

**Comment by wrabcak** [comment]
@rhatdan dan, feel free to do it.

**Comment by rhatdan** [comment]
I will move my repo to projectatomic and then make you an admin.

**Comment by wrabcak** [comment]
But this apply your pull requests. Nice try how to merge it Dan :D

**Comment by rhatdan** [comment]
Done.  You and @mgrepl are admins
